import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ActiveLink from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="flex space-x-4 bg-blue-500 p-4">
					<ActiveLink href="/">Home</ActiveLink>

					<ActiveLink href="/products" exact={false}>
						Products
					</ActiveLink>
				</nav>
				<main className="container mx-auto">{children}</main>
			</body>
		</html>
	);
}
