import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ActiveLink from "@/ui/atoms/ActiveLink";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="bg-blue-500">
					<ul className="container mx-auto flex space-x-4 p-4">
						<li>
							<ActiveLink href="/">Home</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products" exact={false}>
								Products
							</ActiveLink>
						</li>
					</ul>
				</nav>
				<main className="container mx-auto flex-1 p-4">{children}</main>
				<footer className="bg-blue-500 p-4 text-center text-white">© 2024 Muszu</footer>
			</body>
		</html>
	);
}
